parent_config: ./agroqualifier/configs/default.yaml

dataset:
  augmentation:
    RandomHorizontalFlip: True
    RandomVerticalFlip: True
    RandomRotation: True
    RandomResizedCrop: True
    ColorJitter: False

logger:
  run_name: "default_augmentation"