parent_config: ./agroqualifier/configs/default.yaml

dataset:
  augmentation:
    RandomHorizontalFlip: True
    RandomVerticalFlip: False
    RandomRotation: True
    RandomResizedCrop: False
    ColorJitter: False

logger:
  run_name: "default_augmentation"