parent_config: ./agroqualifier/configs/default.yaml

training:
  learning_rate: 0.005
  num_epochs: 20
  gamma: 0.5

dataset:
  augmentation:
    RandomHorizontalFlip: True
    RandomVerticalFlip: False
    RandomRotation: True
    RandomResizedCrop: True
    ColorJitter: False

logger:
  run_name: "default_augmentation"