parent_config: ./agroqualifier/configs/default.yaml

training:
  batch_size: 1
  num_workers: 0
  learning_rate: 0.0001
  num_epochs: 5

dataset:
  dataset_path: "/Users/a.sharshavin/Desktop/skoltech/AgroQaulifier/work/agroqualifier/data/debug_dataset"
  size: 256
  horizontal_flip: 0.5

logger:
  name: "wandb"
  run_name: "debug"