training:
  seed: 42
  batch_size: 8
  num_workers: 4
  learning_rate: 0.0001
  num_epochs: 20
  gamma: 0.95
  weight_decay: 0.005

dataset:
  dataset_path: "/Users/a.sharshavin/Desktop/skoltech/AgroQaulifier/work/Datasets/Mandarins segmentation.v2i.coco"
  size: 512
  horizontal_flip: 0.5
  augmentation:
    RandomHorizontalFlip: True
    RandomVerticalFlip: False
    RandomRotation: False
    RandomResizedCrop: False
    ColorJitter: False
  
model:
 name: "MaskRCNN"
 num_classes: 2 # background and mandarin
 backbone: "resnet50"
 threshold: 0.6

logger:
  name: "wandb"
  run_name: "default"